INSERT INTO users (first_name, last_name, email, password)
VALUES ("John", "Doe", "johnDoe@gmail.com", "111111")
INSERT INTO users (first_name, last_name, email, password)
VALUES ("Jerry", "Dimmer", "jerryDoe@gmail.com", "111112")
INSERT INTO users (first_name, last_name, email, password)
VALUES ("Joey", "Summers", "joeyDoe@gmail.com", "111113")
INSERT INTO users (first_name, last_name, email, password)
VALUES ("Boe", "Duke", "boeDoe@gmail.com", "111114")
INSERT INTO users (first_name, last_name, email, password)
VALUES ("todd", "Randall", "toddDoe@gmail.com", "141111")
INSERT INTO users (first_name, last_name, email, password)
VALUES ("Jeremy", "Conner", "JeremyDoe@gmail.com", "511111")
INSERT INTO users (first_name, last_name, email, password)
VALUES ("Rocky", "Breatie", "rockyDoe@gmail.com", "611111")
INSERT INTO users (first_name, last_name, email, password)
VALUES ("Dawson", "Copeland", "DawsonDoe@gmail.com", "111711")
INSERT INTO users (first_name, last_name, email, password)
VALUES ("Milicent", "Grant", "MilicentDoe@gmail.com", "111181")
INSERT INTO users (first_name, last_name, email, password)
VALUES ("Sally", "Wachowski", "sallyDoe@gmail.com", "1111911")
INSERT INTO users (first_name, last_name, email, password)
VALUES ("Gretchen", "Linus", "GretchenDoe@gmail.com", "111881")
INSERT INTO users (first_name, last_name, email, password)
VALUES ("Terry", "Cruise", "terryDoe@gmail.com", "111771")
INSERT INTO users (first_name, last_name, email, password)
VALUES ("Mal", "Fran", "malDoe@gmail.com", "111551")
INSERT INTO users (first_name, last_name, email, password)
VALUES ("Luke", "Skywalker", "lukeDoe@gmail.com", "441111")
INSERT INTO users (first_name, last_name, email, password)
VALUES ("Don", "Trudee", "donDoe@gmail.com", "111133")
INSERT INTO users (first_name, last_name, email, password)
VALUES ("Chris", "Tomlin", "chrisDoe@gmail.com", "112211")
INSERT INTO users (first_name, last_name, email, password)
VALUES ("Pat", "Lacosta", "patDoe@gmail.com", "1113331")